In [ ]:
import pandas as pd
data1 = pd.read_csv(r"Dataset1.csv")
data1

     User ID  Gender  Age  Estimated Salary  Purchased
0   15624510    Male   19             19000          0
1   15810944    Male   35             20000          0
2   15668575  Female   26             43000          0
3   15603246  Female   27             57000          0
4   15804002    Male   19             76000          0
5   15728773    Male   27             58000          0
6   15598044  Female   27             84000          0
7   15694829  Female   32            150000          1
8   15600575    Male   25             33000          0
9   15277311  Female   35             65000          0
10  15570769  Female   26             80000          0
11  15606274  Female   26             52000          0
12  15746139    Male   20             86000          0
13  15704987    Male   32             18000          0
14  15628972    Male   18             82000          0
15  15697686    Male   29             80000          0
16  15733883    Male   47             25000          1
17  15617482    Male   45             26000          1
18  15704583    Male   46             28000          1
19  15621083  Female   48             29000          1
20  15649487    Male   45             22000          1
21  15736760  Female   47             49000          1

In [ ]:
df = pd.DataFrame(data1,columns=["Age","Estimated Salary"])
df.head()

   Age  Estimated Salary
0   19             19000
1   35             20000
2   26             43000
3   27             57000
4   19             76000

In [ ]:
df['target'] = data1.Purchased
df.head()

   Age  Estimated Salary  target
0   19             19000       0
1   35             20000       0
2   26             43000       0
3   27             57000       0
4   19             76000       0

In [ ]:
from sklearn.model_selection import train_test_split
X = df.drop(['target'], axis='columns')
y = df.target

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [ ]:
len(X_train)

17

In [ ]:
len(X_test)

5

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
knn.score(X_test, y_test)

1.0

In [ ]:
knn.predict([[55,20000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"

array([0])